// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mysteps_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyStepsClient is the client API for MySteps service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyStepsClient interface {
	GetRoute(ctx context.Context, in *MyStepsRequest, opts ...grpc.CallOption) (*MyStepsResponse, error)
}

type myStepsClient struct {
	cc grpc.ClientConnInterface
}

func NewMyStepsClient(cc grpc.ClientConnInterface) MyStepsClient {
	return &myStepsClient{cc}
}

func (c *myStepsClient) GetRoute(ctx context.Context, in *MyStepsRequest, opts ...grpc.CallOption) (*MyStepsResponse, error) {
	out := new(MyStepsResponse)
	err := c.cc.Invoke(ctx, "/mysteps.v1.MySteps/GetRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyStepsServer is the server API for MySteps service.
// All implementations must embed UnimplementedMyStepsServer
// for forward compatibility
type MyStepsServer interface {
	GetRoute(context.Context, *MyStepsRequest) (*MyStepsResponse, error)
	mustEmbedUnimplementedMyStepsServer()
}

// UnimplementedMyStepsServer must be embedded to have forward compatible implementations.
type UnimplementedMyStepsServer struct {
}

func (UnimplementedMyStepsServer) GetRoute(context.Context, *MyStepsRequest) (*MyStepsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoute not implemented")
}
func (UnimplementedMyStepsServer) mustEmbedUnimplementedMyStepsServer() {}

// UnsafeMyStepsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyStepsServer will
// result in compilation errors.
type UnsafeMyStepsServer interface {
	mustEmbedUnimplementedMyStepsServer()
}

func RegisterMyStepsServer(s grpc.ServiceRegistrar, srv MyStepsServer) {
	s.RegisterService(&MySteps_ServiceDesc, srv)
}

func _MySteps_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyStepsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyStepsServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mysteps.v1.MySteps/GetRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyStepsServer).GetRoute(ctx, req.(*MyStepsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MySteps_ServiceDesc is the grpc.ServiceDesc for MySteps service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MySteps_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mysteps.v1.MySteps",
	HandlerType: (*MyStepsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoute",
			Handler:    _MySteps_GetRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "my_steps.proto",
}
