name: terraform-automation

on:
  pull_request:
    types: [ labeled ]

concurrency: 
  group: ${{ github.action == 'terraform-automation' }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: ./terraform

jobs:

  deployment_by_terraform:
    name: 'Creating infra with terraform'
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'create-infra' }}

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/98843203215/locations/global/workloadIdentityPools/guide-my-steps-pool/providers/guide-my-steps-provider'
          service_account: 'terraform@guide-my-steps.iam.gserviceaccount.com'

      # Generates an execution plan for Terraform
      - name: Terraform Apply
        continue-on-error: false
        run: |
          terraform init 
          terraform apply -auto-approve