name: deploying-staging

on:
  pull_request:
    types: [ labeled ]

jobs:
  call-workflow-build-test:
   if: ${{ github.event.label.name == 'deploy-staging' }}
   uses: ./.github/workflows/push-docker-img-reusable.yaml
   secrets:
    repo_token: ${{ secrets.MYTOKEN }}
    docker_user: ${{ secrets.DOCKERHUB_USERNAME }}
    docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
