name: deploying-staging

on:
  pull_request:
    types: [ labeled ]

jobs:
  call-workflow-deploy-staging:
   if: ${{ github.event.label.name == 'deploy-staging' }}
   uses: ./.github/workflows/deploy-to-compute-engine.yaml

