on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3

    #- name: Analyze with SonarCloud
    #  uses: sonarsource/sonarcloud-github-action@master
    #  with:
    #    organization: "<your-organization>"
    #    project: "<your-project>"
    #    token: ${{ secrets.SONAR_TOKEN }}
          # Optional parameters:
          # fail-on-warnings: true
          # coverage-threshold: 80
          # quality-gate-wait: true






