name: push-img-docker

on:
 schedule:
 - cron: "0 10 * * *"

 workflow_call:
    secrets:
      repo_token:
         required: true
      docker_user:
        required: true
      docker_token:
         required: true

env:
   RUN_REGION: europe-west1
   SERVICE_NAME: api
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
     -
      name: Checkout
      uses: actions/checkout@v3
     -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
       # list of Docker images to use as base name for tags
       images: |
         gcarreno/guide-my-steps
         ghcr.io/gcarrenho/guide-my-steps-api
       flavor: latest=true
       # generate Docker tags based on the following events/attributes
       tags: |
         type=schedule
         type=ref,event=branch
         type=ref,event=pr
         type=semver,pattern={{version}}
         type=sha
 #        type=semver,pattern={{major}}.{{minor}}
 #        type=semver,pattern={{major}}
     -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
     -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
     -
       name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_token }}

     -
      name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.repo_token }}
     -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        #tags: gcarreno/guide-my-steps:latest
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

     -
       uses: ./.github/workflows/go-build-test-reusable.yaml
#     - 
#      name: Checkout repository
#      uses: actions/checkout@v3

#     - 
#      id: 'auth'
#      name: 'Authenticate to Google Cloud'
#      uses: 'google-github-actions/auth@v1'
#      with:
#       workload_identity_provider: 'projects/98843203215/locations/global/workloadIdentityPools/guide-my-steps-pool/providers/guide-my-steps-provider'
#       service_account: 'github-action@guide-my-steps.iam.gserviceaccount.com'

#     - 
#      name: 'Set up Cloud SDK'
#      uses: 'google-github-actions/setup-gcloud@v1'

#     - 
#      name: Deploy container to Compute Engine
#      run: |
#        gcloud compute instances update-container testvmcontainer-1 \
#        --container-image ghcr.io/gcarrenho/guide-my-steps-api:sha-e12c6df \
#        --zone us-central1-a
